name: Terraform Pipeline Minikube

on:
  push:
    branches: [ main, develop, staging ]
  pull_request:
    branches: [ main, develop, staging ]

jobs:
  terrraform-pipeline:
    name: Runs on Ubuntu Latest Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check out repository code
        run: echo "Running a command from the Terraform Pipeline"


        
